apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-cicd-app
  namespace: enterprise-cicd

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: enterprise-cicd-app

  template:
    metadata:
      labels:
        app: enterprise-cicd-app

    spec:
      containers:
      - name: enterprise-cicd-app

        image: aswinvtk97/enterprise-cicd-app:initial

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        envFrom:
        - configMapRef:
            name: enterprise-config
        - secretRef:
            name: enterprise-secret

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
