apiVersion: v1
kind: Secret
metadata:
  name: enterprise-secret
  namespace: enterprise-cicd

type: Opaque

stringData:
  DB_USERNAME: admin
  DB_PASSWORD: password123
  JWT_SECRET: enterprise-secret-key
