apiVersion: v1
kind: Service
metadata:
  name: enterprise-cicd-service
  namespace: enterprise-cicd

spec:
  selector:
    app: enterprise-cicd-app

  ports:
  - port: 80
    targetPort: 3000

  type: NodePort
